/**
 * Governed identifiers.
 *
 * Academy entities use UUIDs generated by the server. Users are identified by
 * their Firebase uid (profiles.firebase_uid), which is the canonical identity
 * everywhere in the application. IDs are never reused: a new version, a new
 * record or a restored copy always receives a fresh identifier.
 */
import { DomainError } from "./errors.ts";

export const ENTITY_KINDS = [
  "profile",
  "program",
  "course",
  "curriculum",
  "curriculum_version",
  "unit",
  "lesson",
  "lesson_script",
  "lesson_script_version",
  "lesson_script_annotation",
  "class_group",
  "session",
  "enrollment",
  "attendance_record",
  "task",
  "submission",
  "assessment",
  "assessment_version",
  "assessment_assignment",
  "assessment_attempt",
  "completion",
  "feedback",
  "certificate",
  "library_resource",
  "message",
  "announcement",
  "notification",
  "recording",
  "entitlement",
  "policy_value",
  "approval_gate",
  "teacher_application",
] as const;

export type EntityKind = (typeof ENTITY_KINDS)[number];

export interface EntityRef {
  readonly kind: EntityKind;
  readonly id: string;
}

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/** Firebase uids are 1-128 characters with no whitespace or control characters. */
const UID_PATTERN = /^[^\s\u0000-\u001f\u007f]{1,128}$/;

export function isUuid(value: unknown): value is string {
  return typeof value === "string" && UUID_PATTERN.test(value);
}

export function isUid(value: unknown): value is string {
  return typeof value === "string" && UID_PATTERN.test(value);
}

export function isEntityKind(value: unknown): value is EntityKind {
  return typeof value === "string" && (ENTITY_KINDS as readonly string[]).includes(value);
}

/** Parses a UUID from untrusted input; throws a safe 400 otherwise. */
export function parseUuid(value: unknown, field: string): string {
  if (!isUuid(value)) {
    throw new DomainError("VALIDATION", `${field} must be a valid identifier.`);
  }
  return value.toLowerCase();
}

/** Parses an optional UUID; undefined/null/"" become null. */
export function parseOptionalUuid(value: unknown, field: string): string | null {
  if (value === undefined || value === null || value === "") return null;
  return parseUuid(value, field);
}

/** Parses a Firebase uid from a trusted-but-typed source (never from a request body). */
export function parseUid(value: unknown, field: string): string {
  if (!isUid(value)) {
    throw new DomainError("VALIDATION", `${field} must be a valid user identifier.`);
  }
  return value;
}

/**
 * Builds a validated entity reference. Profiles are keyed by Firebase uid;
 * every other academy entity is keyed by UUID.
 */
export function entityRef(kind: unknown, id: unknown): EntityRef {
  if (!isEntityKind(kind)) {
    throw new DomainError("VALIDATION", "Unknown entity type.");
  }
  const parsedId = kind === "profile" ? parseUid(id, "id") : parseUuid(id, "id");
  return Object.freeze({ kind, id: parsedId });
}

export type IdGenerator = () => string;

export const defaultIdGenerator: IdGenerator = () => globalThis.crypto.randomUUID();

/** Injectable clock returning an ISO-8601 UTC timestamp. */
export type Clock = () => Date;

export const systemClock: Clock = () => new Date();

export function toIso(date: Date): string {
  if (Number.isNaN(date.getTime())) {
    throw new DomainError("VALIDATION", "Invalid date.");
  }
  return date.toISOString();
}

const CORRELATION_ID_PATTERN = /^[A-Za-z0-9._:-]{8,128}$/;

/** Correlation ids group the audit events of one user intent. */
export function parseCorrelationId(value: unknown): string | null {
  if (value === undefined || value === null || value === "") return null;
  if (typeof value !== "string" || !CORRELATION_ID_PATTERN.test(value)) {
    throw new DomainError("VALIDATION", "Invalid correlation identifier.");
  }
  return value;
}
