/** Administrator API paths (all under /api/admin/academy, plus the administrator people directory). */

const e = encodeURIComponent;
const A = "/api/admin/academy";

export const adminApi = {
  overview: `${A}/overview`,
  reviewQueue: `${A}/review-queue`,
  audit: (query: string) => `${A}/audit${query ? `?${query}` : ""}`,
  policies: (programId?: string, courseId?: string) => `${A}/policies${programId || courseId ? `?${new URLSearchParams({ ...(programId ? { programId } : {}), ...(courseId ? { courseId } : {}) })}` : ""}`,
  policy: (key: string) => `${A}/policies/${e(key)}`,
  programs: (includeDeleted = false) => `${A}/programs${includeDeleted ? "?includeDeleted=true" : ""}`,
  program: (id: string) => `${A}/programs/${e(id)}`,
  courses: (includeDeleted = false) => `${A}/courses${includeDeleted ? "?includeDeleted=true" : ""}`,
  course: (id: string) => `${A}/courses/${e(id)}`,
  curriculum: (courseId: string) => `${A}/courses/${e(courseId)}/curriculum`,
  curriculumVersion: (id: string) => `${A}/curriculum-versions/${e(id)}`,
  lessonScript: (lessonId: string) => `${A}/lessons/${e(lessonId)}/script`,
  lessonScriptVersion: (id: string) => `${A}/lesson-script-versions/${e(id)}`,
  assessments: (courseId?: string) => `${A}/assessments${courseId ? `?courseId=${e(courseId)}` : ""}`,
  assessment: (id: string) => `${A}/assessments/${e(id)}`,
  assessmentVersion: (id: string) => `${A}/assessment-versions/${e(id)}`,
  resources: (courseId: string) => `${A}/courses/${e(courseId)}/resources`,
  resource: (id: string) => `${A}/course-resources/${e(id)}`,
  remediationRules: (courseId: string) => `${A}/courses/${e(courseId)}/remediation-rules`,
  remediationRule: (id: string) => `${A}/remediation-rules/${e(id)}`,
  classGroups: (courseId?: string, includeDeleted = false) => {
    const query = new URLSearchParams({ ...(courseId ? { courseId } : {}), ...(includeDeleted ? { includeDeleted: "true" } : {}) }).toString();
    return `${A}/class-groups${query ? `?${query}` : ""}`;
  },
  classGroup: (id: string) => `${A}/class-groups/${e(id)}`,
  sessions: (classGroupId: string) => `${A}/class-groups/${e(classGroupId)}/sessions`,
  session: (id: string) => `${A}/sessions/${e(id)}`,
  preparations: (sessionId: string) => `${A}/sessions/${e(sessionId)}/preparations`,
  sessionRecordings: (sessionId: string) => `${A}/sessions/${e(sessionId)}/recordings`,
  recording: (id: string) => `${A}/recordings/${e(id)}`,
  enrollments: (classGroupId: string) => `${A}/class-groups/${e(classGroupId)}/enrollments`,
  enrollment: (id: string) => `${A}/enrollments/${e(id)}`,
  completion: (enrollmentId: string) => `${A}/enrollments/${e(enrollmentId)}/completion`,
  revokeCompletion: (completionId: string) => `${A}/completions/${e(completionId)}`,
  certificate: (enrollmentId: string) => `${A}/enrollments/${e(enrollmentId)}/certificate`,
  revokeCertificate: (certificateId: string) => `${A}/certificates/${e(certificateId)}`,
  classAssignments: (classGroupId: string) => `${A}/class-groups/${e(classGroupId)}/assignments`,
  assignment: (id: string) => `${A}/assignments/${e(id)}`,
  gateDefinitions: `${A}/approval-gates/definitions`,
  gates: `${A}/approval-gates`,
  gate: (id: string) => `${A}/approval-gates/${e(id)}`,
  announcements: `${A}/announcements`,
  libraries: `${A}/production/libraries`,
  library: (id: string) => `${A}/production/libraries/${e(id)}`,
  factories: `${A}/production/factories`,
  runs: `${A}/production/runs`,
  run: (id: string) => `${A}/production/runs/${e(id)}`,
  items: `${A}/production/items`,
  item: (id: string) => `${A}/production/items/${e(id)}`,
  itemLinks: (id: string) => `${A}/production/items/${e(id)}/links`,
  link: (id: string) => `${A}/production/links/${e(id)}`,
  productionVersion: (id: string) => `${A}/production/versions/${e(id)}`,
  productionReport: `${A}/production/report`,
  people: "/api/admin/users",
};
